spring:
  application:
    name: customer-service

server:
  port: 6161

eureka:
  client:
    serviceUrl:
      defaultZone:  ${EUREKA_URI:http://192.168.50.201:8761/eureka}
  instance:
    prefer-ip-address: true

logging:
    file: customer.log
    level:
      root: 
      project:
          user:
            UserClient: FULL
ribbon:
  eureka:
    enabled: true