spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.50.201:3306/sys-log?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: ruio*W&201
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: 192.168.50.201
    port: 5672
    username: user
    password: password
    publisher-confirms: true
    virtual-host: /

server:
  port: 9997